"""create lotes table

Revision ID: 0fe08474c365
Revises: 40d93b189444
Create Date: 2026-08-26 17:03:28.777999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe08474c365'
down_revision = '40d93b189444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_colheita', sa.Date(), nullable=False),
    sa.Column('quantidade_kg', sa.Float(), nullable=False),
    sa.Column('fermentacao', sa.String(length=100), nullable=False),
    sa.Column('secagem', sa.String(length=100), nullable=False),
    sa.Column('umidade', sa.Float(), nullable=True),
    sa.Column('sistema_producao', sa.String(length=100), nullable=True),
    sa.Column('produtor_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produtor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotes')
    # ### end Alembic commands ###
