"""remove nome from lotes

Revision ID: 3356a372d0c5
Revises: 5147dad02d88
Create Date: 2026-09-03 15:58:00.607102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3356a372d0c5'
down_revision = '5147dad02d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
