"""improve usuario model

Revision ID: 40d93b189444
Revises: c32dfed1a745
Create Date: 2026-07-09 14:29:03.026164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40d93b189444'
down_revision = 'c32dfed1a745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('usuarios_email_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.create_unique_constraint(batch_op.f('usuarios_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
