"""add producer location fields

Revision ID: 5147dad02d88
Revises: 0fe08474c365
Create Date: 2026-08-31 20:49:20.750291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5147dad02d88'
down_revision = '0fe08474c365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('propriedade', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vicinal', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('vicinal')
        batch_op.drop_column('municipio')
        batch_op.drop_column('propriedade')

    # ### end Alembic commands ###
